@baseUrl=http://localhost:5001/authors

POST {{baseUrl}}
Content-Type: application/json



{
        
        "name": "ggggg",
        "surname": "ner",
        "email": "sonero@.it",
        "birthDay" :"ciso",
        "avatar": ""
        
}


###
GET {{baseUrl}}