//@baseUrl=http://localhost:5001/authors

@baseUrl=http://localhost:5001/authors


GET {{baseUrl}}

###
GET {{baseUrl}}/66df34346691399c0a0e563a



###

POST {{baseUrl}}
Content-Type: application/json

{
        
        "name": "miche",
        "surname": "ilaria",
        "email": "u.co@gmail.it",
        "birhDay":"ciao",
        "avatar": ""
        
}

###

PUT {{baseUrl}}/66df34346691399c0a0e563a
Content-Type: application/json


{
        "category": "azzzzzzzzzzzzzzzz "
       
}


###
DELETE {{baseUrl}}/66df34346691399c0a0e563a



